services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

# run it in CMD on windows
docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v C:/Users/vikat/OneDrive/Desktop/NotionAi/de-zoomcamp/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  postgres:13


  #To run the postgres containera and pgadmin in the same network

  #creating the network
  docker network create pgnetwork

  #running the postgres container with the network
  docker run -d \
  --name postgres \
  --network pg_network \
  -e POSTGRES_USER=root \
  -e POSTGRES_PASSWORD=root \
  -e POSTGRES_DB=ny_taxi \
  -v c:/Users/vikat/OneDrive/Desktop/NotionAi/de-zoomcamp/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  postgres:15

#running the pgadmin container with the same network
docker run -d \
--name pgadmin \
--network pg_network \
-e PGADMIN_DEFAULT_EMAIL=  \
-e PGADMIN_DEFAULT_PASSWORD=admin \
-p 5050:80 \
dpage/pgadmin4
