FROM openjdk:8-jdk

# Install Python 3.9, pip, and utilities
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget \
    curl \
    procps \
    && rm -rf /var/lib/apt/lists/*

# Set python3 as default
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# Set JAVA_HOME explicitly (for PySpark)
ENV JAVA_HOME=/usr/local/openjdk-8
ENV PATH=$JAVA_HOME/bin:$PATH

WORKDIR /app

COPY requirements.txt requirements.txt
COPY etl_postgres.py etl_postgres.py
COPY postgresql-42.7.4.jar postgresql-42.7.4.jar
COPY data/ data/

# Upgrade pip and install Python deps
# Download PostgreSQL JDBC driver
# RUN wget https://jdbc.postgresql.org/download/postgresql-42.7.4.jar -O /app/postgresql-42.7.4.jar

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "etl_postgres.py"]


#Run postgres container
# docker run -d \ 
#   --name postgres \ 
#   --network pg_network \ 
#   -e POSTGRES_USER=root \ 
#   -e POSTGRES_PASSWORD=root \ 
#   -e POSTGRES_DB=ny_taxi \ 
#   -v C:/Users/vikat/OneDrive/Desktop/NotionAi/de-zoomcamp/ny_taxi_postgres_data:/var/lib/postgresql/data \ 
#   -p 5432:5432 \ 
#   postgres:13

# #Run pgadmin container
# docker run -d \ 
#   --name pgadmin \ 
#   --network pg_network \ 
#   -e PGADMIN_DEFAULT_EMAIL=admin@admin.com \ 
#   -e PGADMIN_DEFAULT_PASSWORD=admin \ 
#   -p 5050:80 \ 
#   dpage/pgadmin4

# # build docker image and run for etl_postgres.py
# docker build -t etl_postgres:v001 .
# docker run -it --rm --network pg_network etl_postgres:v001 --username=root --password=root --host=postgres --port=5432 --database=ny_taxi

