# Use the official Python image from the Docker Hub
FROM python:3.9-slim
# Set the working directory in the container
WORKDIR /app
# Copy the current directory contents into the container at /app
COPY etl_postgres.py etl_postgres.py
COPY requirements.txt requirements.txt
# Install any needed packages specified in requirements.txt
# Install wget (or any system packages you need)
# Install Java 8, wget, and ps
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk wget procps && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

ENTRYPOINT ["python", "etl_postgres.py"]

#Run postgres container
# docker run -d \ 
#   --name postgres \ 
#   --network pg_network \ 
#   -e POSTGRES_USER=root \ 
#   -e POSTGRES_PASSWORD=root \ 
#   -e POSTGRES_DB=ny_taxi \ 
#   -v C:/Users/vikat/OneDrive/Desktop/NotionAi/de-zoomcamp/ny_taxi_postgres_data:/var/lib/postgresql/data \ 
#   -p 5432:5432 \ 
#   postgres:13

# #Run pgadmin container
# docker run -d \ 
#   --name pgadmin \ 
#   --network pg_network \ 
#   -e PGADMIN_DEFAULT_EMAIL=admin@admin.com \ 
#   -e PGADMIN_DEFAULT_PASSWORD=admin \ 
#   -p 5050:80 \ 
#   dpage/pgadmin4

# # build docker image and run for etl_postgres.py
# docker build -t etl_postgres:v001 .
# docker run -it --rm --network pg_network etl_postgres:v001 --username=root --password=root --host=localhost --port=5432 --database=ny_taxi
