version: '3.8'

services:
  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data"
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    ports:
      - "5050:80"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
